### ISSUE TITLE
InvalidScope

### ISSUE THREAD

**Issue by rquanx** [koltyakov/node-sp-auth-troubleshoot#2]
Hi,

private.json
![image](https://user-images.githubusercontent.com/36622981/80557405-69a54900-8a09-11ea-9924-cb3f7e582d26.png)

error message
```
Connecting to site: https://swirecocacola.sharepoint.cn/sites/scs

=== Error ===
 Error: <s:Fault>
  <s:Code>
    <s:Value>s:Sender</s:Value>
    <s:Subcode>
      <s:Value xmlns:a="http://docs.oasis-open.org/ws-sx/ws-trust/200512">a:InvalidScope</s:Value>
    </s:Subcode>
  </s:Code>
  <s:Reason>
    <s:Text xml:lang="en-US">ID3082: The request scope is not valid or is unsupported.</s:Text>
  </s:Reason>
</s:Fault>
    at config_1.request.post.then.xmlResponse (C:\Users\runquan.tan\Desktop\node-sp-auth-troubleshoot\node_modules\node-sp-auth\lib\src\utils\Adf
sHelper.js:31:23)
    at tryCatcher (C:\Users\runquan.tan\Desktop\node-sp-auth-troubleshoot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\runquan.tan\Desktop\node-sp-auth-troubleshoot\node_modules\bluebird\js\release\promise.js:547:
31)
    at Promise._settlePromise (C:\Users\runquan.tan\Desktop\node-sp-auth-troubleshoot\node_modules\bluebird\js\release\promise.js:604:18)        
    at Promise._settlePromise0 (C:\Users\runquan.tan\Desktop\node-sp-auth-troubleshoot\node_modules\bluebird\js\release\promise.js:649:10)       
    at Promise._settlePromises (C:\Users\runquan.tan\Desktop\node-sp-auth-troubleshoot\node_modules\bluebird\js\release\promise.js:729:18)       
    at _drainQueueStep (C:\Users\runquan.tan\Desktop\node-sp-auth-troubleshoot\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\runquan.tan\Desktop\node-sp-auth-troubleshoot\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\runquan.tan\Desktop\node-sp-auth-troubleshoot\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\runquan.tan\Desktop\node-sp-auth-troubleshoot\node_modules\bluebird\js\release\asy
nc.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Done in 54.77s.
```

**Comment by rquanx** [comment]
fix in node-sp-auth 2.5.8
